@baseUrl = http://localhost:3000


### Usuários - Listar todos os usuários (somente ADMIN)
GET http://localhost:3000/users
Authorization: Bearer <seu_token_jwt>

###

### Usuários - Buscar usuário pelo ID (ADMIN ou dono da conta)
GET http://localhost:3000/users/:id
Authorization: Bearer <seu_token_jwt>

###

### Usuários - Criar novo usuário (recomenda-se só ADMIN)
POST http://localhost:3000/users
Authorization: Bearer <seu_token_jwt>  # Remova essa linha se o endpoint for público
Content-Type: application/json

{
  "email": "novo.usuario@exemplo.com",
  "password": "senhaSegura123",
  "role": "USER",
  "name": "Nome do Usuário"
}

###

### Usuários - Atualizar usuário pelo ID (ADMIN ou dono da conta)
PATCH http://localhost:3000/users/:id
Authorization: Bearer <seu_token_jwt>
Content-Type: application/json

{
  "name": "Nome Atualizado",
  "password": "novaSenha123"
}

###

### Usuários - Deletar usuário pelo ID (somente ADMIN)
DELETE http://localhost:3000/users/:id
Authorization: Bearer <seu_token_jwt>
